site_name: FastTransplant
site_url: https://mdsreq-fga-unb.github.io/2023.1-FastTransplant/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: pt-BR
  palette: 
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.section
    - navigation.path
    - navigation.top
    - tabs

nav:
  - Home: index.md
  - Visão do Produto e Projeto:
    - Visão do Produto: visao-do-produto-e-projeto/visao-do-produto.md
    - Visão do Projeto: visao-do-produto-e-projeto/visao-do-projeto.md
    - Processo de Desenvolvimento: visao-do-produto-e-projeto/processo-de-desenvolvimento.md
    - Lições Aprendidas: visao-do-produto-e-projeto/licoes-aprendidas.md
  - Registros de Reuniões: 
    - Ata e vídeos: atas-e-videos/registros-reunioes.md
    - Ata do dia 13/05: atas-e-videos/13-05.md 
    - Ata do dia 30/05: atas-e-videos/30-05.md 
    - Ata do dia 17/06: atas-e-videos/17-06.md 
    - Ata do dia 29/06: atas-e-videos/29-06.md 
    - Ata do dia 06/07: atas-e-videos/06-07.md 
  - Requisitos do Produto: 
    - Definition of Done: requisitos-do-produto/dod.md
    - Definition of Ready: requisitos-do-produto/dor.md
    - Critérios de aceitação: requisitos-do-produto/criterios-de-aceitacao.md
    - Backlog: requisitos-do-produto/productbacklog.md
  - Entregas das Unidades: 
    - Unidade 1:
      - Pitch RAD: entregas/unidade 1/pitch-rad.md 
      - Diagrama de Ishikawa: entregas/unidade 1/ishiwaka.md 
      - Processo de ER: entregas/unidade 1/processo-ER.md
    - Unidade 2:
      - Mural: entregas/unidade 2/mural.md
      - Tabela priorização de US: entregas/unidade 2/tabela priorizacao.md
    - Unidade 3:
      - Canvas PBB: entregas/unidade 3/canvas-pbb.md
      - SAFe: entregas/unidade 3/safe.md
    - Unidade 4:
      - User Story Mapping: entregas/unidade 4/usm.md
      - Casos de Uso: entregas/unidade 4/casos-de-uso.md
      - Especificações de UCs: 
        - Aprovar transplante: entregas/unidade 4/especificacoes/aprovar-transplante.md
        - Buscar dados: entregas/unidade 4/especificacoes/buscar-dados.md
        - Visualizar registro: entregas/unidade 4/especificacoes/visualizar-registro.md
    - Vídeos: entregas/videos/videos.md

    

